language: perl
perl:
    - "5.18"
    - "5.16"
    - "5.14"
    - "5.12"
    - "5.10"
before_install:
    - "cpanm --installdeps ."
    - "cpanm Test::More"
    - "cpanm Devel::Cover::Report::Coveralls"
script:
  - prove -l t/*
