requires 'DBI';
requires 'DBD::mysql';
requires 'Plack';
requires 'Template::Toolkit', '2.24';
requires 'Template::Plugin::FillInForm';
requires 'DBIx::Class', '0.08210';
requires 'DBIx::Class::Schema::Loader', '0.07035';
requires 'DBIx::Class::InflateColumn::Serializer';
requires 'Moo';
requires 'MooX::Types::MooseLike::Base';
requires 'MooX::Options';
requires 'Mojolicious', '3.94';
requires 'Mojolicious::Plugin::Recaptcha';
requires 'Mojolicious::Plugin::TtRenderer';
requires 'Mojolicious::Plugin::BasicAuth';
requires 'Mojolicious::Plugin::Web::Auth';
requires 'Data::UUID';
requires 'Module::Runtime';
requires 'WWW::Sitemap::XML';
requires 'JSON::XS';
requires 'XML::Feed';
requires 'Date::Manip';
requires 'Sphinx::Search';
requires 'Net::Delicious';
requires 'Facebook::Graph';
requires 'MIME::Lite';
requires 'Locale::Codes::Country', '3.25';
requires 'Proc::PID::File';

## scrape
requires 'Log::Dispatchouli';
requires 'HTML::FormatText';
requires 'WWW::LinkedIn';